### ISSUE TITLE
Wiremod Conflict

### ISSUE THREAD

**Issue by XxWestKillzXx** [tyguy550/BackDoorFinder#1]
With this active it seems to make a lot of spam in the server console and E2 crashes the server. Here's some of the stuff that's spammed into console.

RunString ran: lua/entities/gmod_wire_expression2/base/compiler.lua //
    RunString(string.format("Compiler.native = function(self) return self.Scopes[%i][%q] end", ScopeID, args[3])) -- This Line! - severe

RunString ran: lua/entities/gmod_wire_expression2/base/compiler.lua //
    RunString("Compiler.native = function() return " .. args[3] .. " end") - severe

pcall ran: entities/gmod_wire_expression2/core/core.lua

pcall ran: lua/entities/gmod_wire_expression2/init.lua //
    local ok, ret = pcall(self.CallHook, self, ...) - severe

**Comment by alexjohnyoung** [comment]
what this addon does, is when a function on the table is ran, it sends a notification that it was ran. there's nothing i can do about this. you can add a exclusion to it if you check where the file is and check if it's that file

**Comment by XxWestKillzXx** [comment]
Ah okay, thanks for your help.
